openapi: 3.1.0
info:
  version: 1.0.0
  title: Money guard app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is documentation of Money guard app
tags:
  - name: Transactions
    description: Operations about Transactions
  - name: Auth
    description: Authentication Operations
servers:
  - url: http://localhost:3000
  - url: https://project-devstudents-node-js.onrender.com
paths:
  /transactions:
    get:
      $ref: ../swagger/paths/transactions/get.yaml

    post:
      $ref: ../swagger/paths/transactions/post.yaml

  /transactions/{id}:
    patch:
      $ref: ../swagger/paths/transactions/{id}/patch.yaml

    delete:
      $ref: ../swagger/paths/transactions/{id}/delete.yaml

  /transactions/categories:
    get:
      $ref: ../swagger/paths/transactions/categories/get.yaml

  /transactions/summary:
    get:
      $ref: ../swagger/paths/transactions/summary/get.yaml

  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml

  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml

  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml

  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh/post.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

    cookieAuth:
      type: apiKey
      in: cookie
      name: refreshToken
